background_opacity          0.6
cursor_trail                1
window_padding_width        0
font_size 14
dynamic_background_opacity yes
#include themes/noctalia.conf

remember_window_size  no
initial_window_width  800
initial_window_height 500

# BEGIN_KITTY_FONTS
font_family      family="MesloLGL Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
# CJK 字符强制使用 Sarasa Term SC（等宽对齐，拉丁仍为上方字体）




# BEGIN_KITTY_THEME
# YsDark
include current-theme.conf
# END_KITTY_THEME